# Generated by Django 6.0.3 on 2026-03-05 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionFunnel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("sessions", models.PositiveIntegerField(default=0)),
                ("product_views", models.PositiveIntegerField(default=0)),
                ("cart_adds", models.PositiveIntegerField(default=0)),
                ("checkout_starts", models.PositiveIntegerField(default=0)),
                ("purchases", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "analytics_conversion_funnel",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DailySalesSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_orders", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_refunds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "net_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("new_customers", models.PositiveIntegerField(default=0)),
                ("items_sold", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analytics_daily_sales",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("product_view", "Product View"),
                            ("add_to_cart", "Add to Cart"),
                            ("remove_from_cart", "Remove from Cart"),
                            ("search", "Search"),
                            ("checkout_start", "Checkout Start"),
                            ("purchase", "Purchase"),
                        ],
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_events",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "occurred_at"],
                        name="analytics_e_event_t_7b4dc8_idx",
                    ),
                    models.Index(
                        fields=["user", "occurred_at"],
                        name="analytics_e_user_id_d1afb9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("add_to_carts", models.PositiveIntegerField(default=0)),
                ("purchases", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_product_performance",
                "ordering": ["-date"],
                "unique_together": {("product", "date")},
            },
        ),
    ]
