# Generated by Django 6.0.3 on 2026-09-04 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
        ("catalog", "0018_product_kind_listing"),
        ("storefronts", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productperformance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="conversionfunnel",
            name="storefront",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conversion_funnels",
                to="storefronts.storefront",
            ),
        ),
        migrations.AddField(
            model_name="dailysalessnapshot",
            name="storefront",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="daily_sales_snapshots",
                to="storefronts.storefront",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="storefront",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analytics_events",
                to="storefronts.storefront",
            ),
        ),
        migrations.AddField(
            model_name="productperformance",
            name="storefront",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_performance",
                to="storefronts.storefront",
            ),
        ),
        migrations.AlterField(
            model_name="conversionfunnel",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="dailysalessnapshot",
            name="date",
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name="conversionfunnel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("storefront__isnull", False)),
                fields=("storefront", "date"),
                name="unique_storefront_conversion_funnel",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversionfunnel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("storefront__isnull", True)),
                fields=("date",),
                name="unique_legacy_conversion_funnel",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailysalessnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("storefront__isnull", False)),
                fields=("storefront", "date"),
                name="unique_storefront_daily_sales",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailysalessnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("storefront__isnull", True)),
                fields=("date",),
                name="unique_legacy_daily_sales",
            ),
        ),
        migrations.AddConstraint(
            model_name="productperformance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("storefront__isnull", False)),
                fields=("storefront", "product", "date"),
                name="unique_storefront_product_performance",
            ),
        ),
        migrations.AddConstraint(
            model_name="productperformance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("storefront__isnull", True)),
                fields=("product", "date"),
                name="unique_legacy_product_performance",
            ),
        ),
    ]
