# Generated by Django 6.0.3 on 2026-09-04 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storefront',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('general', 'General'), ('dispensary', 'Dispensary'), ('hash', 'Hash'), ('peptides', 'Peptides'), ('footwear', 'Footwear')], default='general', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('frontend_url', models.URLField(blank=True)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'storefronts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StorefrontDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='storefronts.storefront')),
            ],
            options={
                'db_table': 'storefront_domains',
            },
        ),
        migrations.CreateModel(
            name='StorefrontOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.URLField(help_text='Exact allowed browser origin, without a trailing slash.', unique=True)),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='storefronts.storefront')),
            ],
            options={
                'db_table': 'storefront_origins',
            },
        ),
    ]
