# Generated by Django 6.0.3 on 2026-09-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefronts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefront',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='storefront',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='storefront',
            name='order_notification_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='storefront',
            name='postal_address',
            field=models.TextField(blank=True),
        ),
    ]
