# Generated by Django 6.1 on 2026-09-01 23:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('content_text', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blog_posts',
                'ordering': ['-published_at'],
            },
        ),
    ]
