# Generated by Django 6.0.3 on 2026-09-04 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blogpost_read_time_and_index"),
        ("storefronts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="storefront",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="blog_posts",
                to="storefronts.storefront",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(max_length=220),
        ),
        migrations.AddConstraint(
            model_name="blogpost",
            constraint=models.UniqueConstraint(
                condition=models.Q(("storefront__isnull", False)),
                fields=("storefront", "slug"),
                name="unique_storefront_blog_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="blogpost",
            constraint=models.UniqueConstraint(
                condition=models.Q(("storefront__isnull", True)),
                fields=("slug",),
                name="unique_legacy_blog_slug",
            ),
        ),
    ]
