# Generated by Django 6.0.3 on 2026-08-29 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("shipping", "0002_shippingmethod_shipment_shipping_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shipping.shippingmethod",
            ),
        ),
    ]
