# Generated by Django 6.0.3 on 2026-09-04 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_payment_method"),
        ("payments", "0003_seed_inactive_payment_methods"),
        ("promotions", "0001_initial"),
        ("shipping", "0004_seed_fedex_shipping_method"),
        ("users", "0003_user_is_guest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "-created_at"], name="orders_status_f8c8df_idx"
            ),
        ),
    ]
