# Generated by Django 6.0.3 on 2026-09-04 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_warehouse_storefront'),
        ('orders', '0005_cart_storefront_order_storefront_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.warehouse'),
        ),
    ]
