# Generated by Django 6.0.3 on 2026-09-04 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0018_product_kind_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CannabisProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, max_length=50)),
                ('strain_type', models.CharField(blank=True, max_length=50)),
                ('thc_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('cbd_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('terpenes', models.JSONField(blank=True, default=dict)),
                ('effects', models.JSONField(blank=True, default=list)),
                ('coa_url', models.URLField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cannabis_profile', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_cannabis_profiles',
            },
        ),
    ]
