# Generated by Django 6.0.3 on 2026-09-04 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0018_product_kind_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeptideProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(blank=True, max_length=500)),
                ('molecular_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('purity_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('form', models.CharField(blank=True, max_length=100)),
                ('concentration', models.CharField(blank=True, max_length=100)),
                ('storage_requirements', models.TextField(blank=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peptide_profile', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_peptide_profiles',
            },
        ),
    ]
