# Generated by Django 6.0.3 on 2026-03-06 22:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_category_image_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariantImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="products/variants/images/")),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "variant_images",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="VariantVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "video_type",
                    models.CharField(
                        choices=[
                            ("upload", "Direct Upload"),
                            ("youtube", "YouTube"),
                            ("vimeo", "Vimeo"),
                        ],
                        default="upload",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="products/variants/videos/"
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/variants/video_thumbnails/",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "variant_videos",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
