# Generated by Django 6.0.3 on 2026-03-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_variantimage_variantvideo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="image",
        ),
    ]
