# Generated by Django 6.0.3 on 2026-04-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_productvariant_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="alt_text",
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
