# Generated by Django 6.0.3 on 2026-04-08 22:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_remove_productimage_alt_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "attribute_types",
            },
        ),
        migrations.AlterField(
            model_name="attribute",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="catalog.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="attribute_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="values",
                to="catalog.attributetype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attribute",
            unique_together={("variant", "attribute_type")},
        ),
        migrations.RemoveField(
            model_name="attribute",
            name="name",
        ),
    ]
