# Generated by Django 6.0.3 on 2026-07-15 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_attributetype_alter_attribute_variant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        help_text="Passed through as-is from the source — not downloaded/re-hosted.",
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "brands",
            },
        ),
        migrations.CreateModel(
            name="Effect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "db_table": "effects",
            },
        ),
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "potency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mild", "Mild"),
                            ("medium", "Medium"),
                            ("strong", "Strong"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "thc_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "thca_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "cbd_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "cbda_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "cbn_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "cbg_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("terpenes", models.JSONField(blank=True, default=dict)),
                (
                    "coa_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to third-party Certificate of Analysis, if hosted externally.",
                    ),
                ),
                (
                    "coa_file",
                    models.FileField(blank=True, null=True, upload_to="lab_reports/"),
                ),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "product_labs",
            },
        ),
        migrations.CreateModel(
            name="ProductDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed Amount")],
                        max_length=10,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=8)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "days_of_week",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="0=Sun..6=Sat, empty=every day",
                    ),
                ),
                ("is_stackable", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_discounts",
            },
        ),
    ]
