# Generated by Django 6.0.3 on 2026-07-15 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_brand_effect_lab_productdiscount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.brand",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cannabis_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sativa", "Sativa"),
                    ("indica", "Indica"),
                    ("hybrid", "Hybrid"),
                    ("hybrid_sativa", "Hybrid (Sativa Leaning)"),
                    ("hybrid_indica", "Hybrid (Indica Leaning)"),
                    ("na", "N/A"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="compliance_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flower", "Flower"),
                    ("vaporizers", "Vaporizers"),
                    ("edibles", "Edibles"),
                    ("concentrates", "Concentrates"),
                    ("pre_rolls", "Pre-Rolls"),
                    ("tinctures", "Tinctures"),
                    ("topicals", "Topicals"),
                    ("beverages", "Beverages"),
                    ("accessories", "Accessories"),
                    ("merchandise", "Merchandise"),
                    ("cbd_products", "CBD Products"),
                    ("gift_cards", "Gift Cards"),
                ],
                help_text="Regulatory product type — distinct from the display Category.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="effects",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="catalog.effect"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="external_source_id",
            field=models.CharField(
                blank=True,
                help_text="POS / scrape source ID — used to upsert on re-import instead of duplicating.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="sub_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="units_sold_hint",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Informational popularity signal from source data, not order history.",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="Passed through as-is from the source — not downloaded/re-hosted.",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="weight_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("grams", "Grams"),
                    ("milligrams", "Milligrams"),
                    ("each", "Each"),
                    ("unknown", "Unknown"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="weight_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
    ]
