# Generated by Django 6.0.3 on 2026-07-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_brand_product_cannabis_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/images/"
            ),
        ),
    ]
