# Generated by Django 6.0.3 on 2026-08-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_productimage_alt_text_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="categories/images/"
            ),
        ),
    ]
