# Generated by Django 6.0.3 on 2026-08-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_category_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name", "id"], "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="effect",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="categories/images/"
            ),
        ),
    ]
