# Generated by Django 6.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_brand_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="meta_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="brand",
            name="meta_title",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_title",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
