# Generated by Django 6.1 on 2026-09-02 01:04

from django.db import migrations, models


def copy_category_fk_into_m2m(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    for product in Product.objects.exclude(category__isnull=True).iterator():
        product.categories.add(product.category_id)


def noop_reverse(apps, schema_editor):
    # categories -> category was a lossy direction to begin with (a product
    # could end up in more than one category); nothing sane to restore here.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_brand_meta_description_brand_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_key',
            field=models.BooleanField(default=False, help_text='Main taxonomy category (Flower, Edibles, ...) as opposed to a promotional/seasonal section used to curate the shop page.'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.category'),
        ),
        migrations.RunPython(copy_category_fk_into_m2m, noop_reverse),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
