# Generated by Django 6.0.3 on 2026-09-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_promote_key_categories_to_roots"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "-created_at"], name="products_is_acti_b753ec_idx"
            ),
        ),
    ]
