# Generated by Django 6.0.3 on 2026-09-04 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_products_is_acti_b753ec_idx'),
        ('storefronts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('general', 'General'), ('cannabis', 'Cannabis'), ('peptide', 'Peptide'), ('footwear', 'Footwear')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('compare_at_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('categories', models.ManyToManyField(blank=True, related_name='listings', to='catalog.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='catalog.product')),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='storefronts.storefront')),
            ],
            options={
                'db_table': 'catalog_listings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['storefront', 'is_active', '-created_at'], name='catalog_lis_storefr_ad2ea0_idx')],
                'constraints': [models.UniqueConstraint(fields=('storefront', 'product'), name='unique_product_per_storefront'), models.UniqueConstraint(fields=('storefront', 'slug'), name='unique_listing_slug_per_storefront')],
            },
        ),
    ]
