# Generated by Django 6.0.3 on 2026-09-04 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0001_initial"),
        ("storefronts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="storefront",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coupons",
                to="storefronts.storefront",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.UniqueConstraint(
                condition=models.Q(("storefront__isnull", False)),
                fields=("storefront", "code"),
                name="unique_storefront_coupon_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.UniqueConstraint(
                condition=models.Q(("storefront__isnull", True)),
                fields=("code",),
                name="unique_legacy_coupon_code",
            ),
        ),
    ]
