# Generated by Django 6.0.3 on 2026-04-08 01:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("carrier", models.CharField(max_length=50)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("estimated_days_min", models.PositiveSmallIntegerField()),
                ("estimated_days_max", models.PositiveSmallIntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "shipping_methods",
                "ordering": ["price"],
            },
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments",
                to="shipping.shippingmethod",
            ),
        ),
    ]
