# Generated by Django 6.0.3 on 2026-09-04 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0004_seed_fedex_shipping_method"),
        ("storefronts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingmethod",
            name="storefront",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipping_methods",
                to="storefronts.storefront",
            ),
        ),
    ]
