# Generated by Django 6.0.3 on 2026-09-06 19:55

from django.db import migrations, models


def copy_shipping_method_scopes(apps, schema_editor):
    ShippingMethod = apps.get_model('shipping', 'ShippingMethod')
    for method in ShippingMethod.objects.exclude(storefront_id=None).iterator():
        method.is_global = False
        method.save(update_fields=['is_global'])
        method.storefronts.add(method.storefront_id)


def restore_shipping_method_scopes(apps, schema_editor):
    ShippingMethod = apps.get_model('shipping', 'ShippingMethod')
    for method in ShippingMethod.objects.filter(is_global=False).iterator():
        method.storefront_id = method.storefronts.values_list('id', flat=True).first()
        method.save(update_fields=['storefront'])


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_shippingmethod_storefront'),
        ('storefronts', '0002_storefront_from_email_storefront_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='is_global',
            field=models.BooleanField(default=True, help_text='Make this method available to every storefront.'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='storefronts',
            field=models.ManyToManyField(blank=True, help_text="Used only when 'is global' is disabled.", related_name='shipping_methods', to='storefronts.storefront'),
        ),
        migrations.RunPython(copy_shipping_method_scopes, restore_shipping_method_scopes),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='storefront',
        ),
    ]
