# Generated by Django 6.0.3 on 2026-09-04 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
        ("storefronts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="storefront",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chat_rooms",
                to="storefronts.storefront",
            ),
        ),
    ]
