# Generated by Django 6.0.3 on 2026-09-04 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_seed_inactive_payment_methods"),
        ("storefronts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="storefront",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_methods",
                to="storefronts.storefront",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name="paymentmethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("storefront__isnull", False)),
                fields=("storefront", "slug"),
                name="unique_storefront_payment_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentmethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("storefront__isnull", True)),
                fields=("slug",),
                name="unique_legacy_payment_slug",
            ),
        ),
    ]
