# Generated by Django 6.0.3 on 2026-09-06 19:55

from django.db import migrations, models


def copy_payment_method_scopes(apps, schema_editor):
    PaymentMethod = apps.get_model('payments', 'PaymentMethod')
    for method in PaymentMethod.objects.exclude(storefront_id=None).iterator():
        method.is_global = False
        method.save(update_fields=['is_global'])
        method.storefronts.add(method.storefront_id)


def restore_payment_method_scopes(apps, schema_editor):
    PaymentMethod = apps.get_model('payments', 'PaymentMethod')
    for method in PaymentMethod.objects.filter(is_global=False).iterator():
        method.storefront_id = method.storefronts.values_list('id', flat=True).first()
        method.save(update_fields=['storefront'])


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentmethod_storefront_alter_paymentmethod_slug_and_more'),
        ('storefronts', '0002_storefront_from_email_storefront_logo_url_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentmethod',
            name='unique_storefront_payment_slug',
        ),
        migrations.RemoveConstraint(
            model_name='paymentmethod',
            name='unique_legacy_payment_slug',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_global',
            field=models.BooleanField(default=True, help_text='Make this method available to every storefront.'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='storefronts',
            field=models.ManyToManyField(blank=True, help_text="Used only when 'is global' is disabled.", related_name='payment_methods', to='storefronts.storefront'),
        ),
        migrations.RunPython(copy_payment_method_scopes, restore_payment_method_scopes),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='storefront',
        ),
    ]
