# Generated by Django 6.0.3 on 2026-09-04 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0018_product_kind_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootwearProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('style_code', models.CharField(blank=True, max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('size_system', models.CharField(blank=True, max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like new'), ('used', 'Used')], default='new', max_length=20)),
                ('authenticity_status', models.CharField(blank=True, max_length=50)),
                ('box_condition', models.CharField(blank=True, max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='footwear_profile', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_footwear_profiles',
            },
        ),
    ]
